''' Even Fibonacci numbers
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
'''


def problem002():
    ''' One can prove that the result can be expressed by the formula
        result = (Gn + Gn+1 - 2 ) / 4
        where Gn is the fibonacci number in place 3*n, such that:
        0, 2, 8, 34, 144, ...
        So we calculate based on that.
    '''
    first, second, result = 0, 2, 0
    while second < 4000000:
        print(second)
        first, second, result = second, first + 4 * second, result + second
    return result
